/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HttpServer: typeof import('./src/components/http-server.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeftMenu: typeof import('./src/components/layout/left-menu.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Logger: typeof import('./src/components/logger.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PickList: typeof import('primevue/picklist')['default']
    RightPannel: typeof import('./src/components/layout/right-pannel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Service: typeof import('./src/components/service.vue')['default']
    SocketioClient: typeof import('./src/components/socketio-client.vue')['default']
  }
}
