/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/config': RouteRecordInfo<'/config', '/config', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/msg/': RouteRecordInfo<'/msg/', '/msg', Record<never, never>, Record<never, never>>,
    '/task/': RouteRecordInfo<'/task/', '/task', Record<never, never>, Record<never, never>>,
    '/task/edit': RouteRecordInfo<'/task/edit', '/task/edit', Record<never, never>, Record<never, never>>,
  }
}
